name: wf3

on:
  push:
    branches:
      - b1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Run a Command
      run: echo "Hello, GitHub Actions!"
